version: '3'
services:
  vue-musicplayer:
    build:
      context: .
      dockerfile: Dockerfile
    # target: production
    # command: npm run start
    container_name: vue_musicplayer
    restart: always
    ports:
      - '80'
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - nginxproxyman
networks:
  nginxproxyman:
    external: true